### ISSUE TITLE
Error when im trying to run Wiom 1.3.4

### ISSUE THREAD

**Issue by 4pol0** [tucnakomet1/Python-Who-Is-On-My-WiFi#11]
I was trying to run Wiom on my OS ( debian based ) and i had a problem beacuse when i typed "wiom -w" it appeared an error that you can see in the image below. 

I look into the code and i saw that there are a few lines that are comments that are not commented i think. How i can fix that?

Thank you : )

![imagen](https://user-images.githubusercontent.com/100537057/168179796-4f121229-b1ee-4e68-aa39-49fe50172f00.png)

**Comment by tucnakomet1** [comment]
I'm so sorry about that, the reason is that I screwed up git merge... Surely you can comment on the parts that report `invalid syntax`. I thought I had uploaded the fixed version to Github... Where and when did you download it - what version is it? 
Alternatively, try cloning the repository and installing it directly from there.

PS: I found more bugs in the code, I'm planning an update for early June.

**Comment by 4pol0** [comment]
Hi, sorry for the late respond.

I tried to comment those "strange" lines but i couldn´t run it anyway.  That error occurs to me in version 1.3.4.  So i decided to try with version 1.3.3. I did the git clone and i ran it, it was everything okey, you can run this version without any problem. But what i saw is when you try to run for example "sudo wiom -w" ,it nothing happens  and i try that with every option of the manual.

**Comment by tucnakomet1** [comment]
I've published a new release (version 1.3.5) in which I fixed a few bugs. Now everything should work properly. 
Please let me know if your problem was solved by installing the new version so we can close the issue.

Thank you.

**Comment by 4pol0** [comment]
Hi, i have tried again with the newest version and now it works perfect. 
Thank you so much.

**Comment by tucnakomet1** [comment]
Perfect, thank you.
